import io
import json
import sys

import pytest

from entanglement import javascript_schema
from entanglement.javascript_schema import __main__ as javascript_schema_main


class SchemaItem:
    _sync_properties = {'id': None, 'name': None}
    sync_primary_keys = ('id',)


class Registry:
    registry = {'Example': SchemaItem}


def test_generate_schema_for_esm_includes_header_and_export():
    output = io.StringIO()

    javascript_schema.generate_schema_for(Registry(), output, type='esm')

    assert output.getvalue() == '''// This file is auto-generated by entanglement.javascript_schema. DO NOT EDIT.

function register_schema(registry) {
        registry._schemaItem( "Example", ["id"], ["id", "name"])
}
export default register_schema;
'''


@pytest.mark.parametrize(
    ('type', 'package_type', 'export'),
    [('esm', 'module', 'export default register_schema;'),
     ('cjs', 'commonjs', 'module.exports = register_schema;')],
)
def test_output_js_schemas_uses_requested_module_type(
        tmp_path, monkeypatch, type, package_type, export):
    registry = Registry()
    monkeypatch.setattr(
        javascript_schema, '_js_regmap',
        {registry: javascript_schema.JsRegEntry(registry, 'example.js')})
    output_directory = tmp_path / 'schemas'
    output_directory.mkdir()
    (output_directory / 'package.json').write_text(
        '{"name": "schema-output", "type": "wrong"}')

    javascript_schema.output_js_schemas(output_directory, type=type)

    assert json.loads((output_directory / 'package.json').read_text()) == {
        'type': package_type, 'private': True}
    schema = (output_directory / 'example').with_suffix('.js').read_text()
    assert schema.startswith('// This file is auto-generated')
    assert schema.rstrip().endswith(export)


def test_output_js_schemas_rejects_unknown_module_type(tmp_path):
    with pytest.raises(ValueError, match="either 'esm' or 'cjs'"):
        javascript_schema.output_js_schemas(tmp_path, type='invalid')


@pytest.mark.parametrize('option', ['--type', '--tye'])
def test_command_line_type_option(monkeypatch, option):
    calls = []
    monkeypatch.setattr(javascript_schema_main, 'output_js_schemas',
                        lambda directory, type: calls.append((directory, type)))
    monkeypatch.setattr(sys, 'argv', ['javascript_schema', '--out', 'schemas', option, 'esm'])

    javascript_schema_main.main()

    assert calls == [('schemas', 'esm')]
