#!/usr/bin/python3
# Copyright (C) 2017, 2018, 2019, 2020, Hadron Industries, Inc.
# Entanglement is free software; you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License version 3
# as published by the Free Software Foundation. It is distributed
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the file
# LICENSE for details.

import dataclasses, json, os, os.path
from ..interface import SyncRegistry

_MODULE_TYPES = {'esm': 'module', 'cjs': 'commonjs'}
_GENERATED_HEADER = ('// This file is auto-generated by '
                     'entanglement.javascript_schema. DO NOT EDIT.\n\n')


def generate_schema_for(registry: SyncRegistry, f, type='cjs'):
    ''':param registry:  A :class:`.SyncRegistry` to output javascript schema for.

    :param f: A file-like object to write the schema to.

    Outputs an ESM or CommonJS module exporting a function of one parameter
    (a Javascript *SyncRegistry*) against which schema information
    will be imported from the Python *SyncRegistry* class.  The schema
    information includes each class registered with the Python
    registry, class :class:`~interface.SyncProperty` and primary key
    information.  Javascript registries and Python registries do not
    share inheritance information.

    :param type: The module format: ``'esm'`` or ``'cjs'``.

    '''

    if type not in _MODULE_TYPES:
        raise ValueError("type must be either 'esm' or 'cjs'")

    js = json.dumps
    f.write(_GENERATED_HEADER)
    f.write('function register_schema(registry) {\n')
    for name, c in registry.registry.items():
        attributes = list(c._sync_properties.keys())
        keys = c.sync_primary_keys
        f.write( f'\
        registry._schemaItem( {js(name)}, {js(keys)}, {js(attributes)})\n')
    f.write('}\n')
    if type == 'esm':
        f.write('export default register_schema;\n')
    else:
        f.write('module.exports = register_schema;\n')

_js_regmap = {}

@dataclasses.dataclass
class JsRegEntry:
    registry: SyncRegistry
    file: str

    
def javascript_registry(registry, file):
    if not file.endswith('.js'):
        file = file+'.js'

    entry = JsRegEntry(registry = registry, file = file)
    _js_regmap[registry] = entry



def output_js_schemas(directory, type='cjs'):
    '''Output registered Javascript schemas to *directory*.

    :param type: The module format: ``'esm'`` or ``'cjs'``.
    '''
    if type not in _MODULE_TYPES:
        raise ValueError("type must be either 'esm' or 'cjs'")

    j = os.path.join
    os.makedirs(directory, exist_ok = True)
    # Ensure Node resolves generated schemas using their selected format.
    package_json_path = j(directory, 'package.json')
    with open(package_json_path, 'wt') as out:
        json.dump({'type': _MODULE_TYPES[type], 'private': True}, out,
                  indent=2)
        out.write('\n')
    for reg, entry in _js_regmap.items():
        os.makedirs(os.path.dirname(j(directory,entry.file)), exist_ok = True)
        with open(j(directory, entry.file), 'wt') as out:
            generate_schema_for(reg, out, type=type)

    

__all__ = 'output_js_schemas javascript_registry generate_schema_for'.split()
